### ISSUE TITLE
[Retail] Achievement date disappear in zhTW client because anchor frame is wrong

### ISSUE THREAD

**Issue by EKE00372** [Stanzilla/WoWUIBugs#360]
it keeps from beta to retail and i just notice it's not a change, actually a bug...... O.o

![6R)$(YKKDT~N9BH F(_9C_C](https://user-images.githubusercontent.com/1412472/204355051-8c1dcfb2-29f8-4c55-ba68-d8b57ceafce5.jpg)

**Comment by Meorawr** [comment]
For reference - the issue here is that the `"$parent"` string for the SetPoint call in zhTW's AchievementButton_Localize function is evaluating to what I'm assuming is the only frame in its parent hierarchy with a defined (global) name. Using a reference to the actual parent (`button.Shield`) should resolve this.

```diff
index fae9d43..7dcc5e5 100644
--- a/Interface/AddOns/Blizzard_AchievementUI/Localization_TW.lua
+++ b/Interface/AddOns/Blizzard_AchievementUI/Localization_TW.lua
@@ -27,7 +27,7 @@ end
 
 function AchievementButton_Localize (button)
 	button.DateCompleted:SetWidth(80);
-	button.DateCompleted:SetPoint("TOP", "$parent", "BOTTOM", -2, 6);
+	button.DateCompleted:SetPoint("TOP", button.Shield, "BOTTOM", -2, 6);
 	button.DateCompleted:SetJustifyH("CENTER");
 	button.Description:SetFontObject("AchievementFont_Small");
 	button.HiddenDescription:SetFontObject("AchievementFont_Small");
```

**Comment by EKE00372** [comment]
Thanks for reply, I've do a temp fix for myself before, but it seems still didn't fix in 10.0.5 PTR.

The cause of issue can be traced back to beta -- I extract blizzard interface code with 10 client, it seems `Blizzard_AchievementUI/Localization` in other language client are all get cleaned but zhTW didn't. Old stuff cause zhTW AchievementUI broke until pre-patch release, and now cause it still have issue without error.

Also actually many unneed style/layout change in `Blizzard_AchievementUI/Localization`, even there is another issue about zhTW use wrong font object and make font lose its shadow offset style.

zhTW: no shadow offset
![image](https://user-images.githubusercontent.com/1412472/208509899-9bb6f4fd-0b14-4437-8de4-dfba193c923a.png)
other client are correct, ex: zhCN
![image](https://user-images.githubusercontent.com/1412472/208509804-df10a8e0-59ff-4d6b-98b0-6f38cf564f14.png)


```
button.Description:SetFontObject("AchievementFont_Small");
button.HiddenDescription:SetFontObject("AchievementFont_Small");
```
should be
```
button.Description:SetFontObject("GameFontHighlight")
button.HiddenDescription:SetFontObject("GameFontHighlight")
```

this is my temp fix
```
LoadAddOn("Blizzard_AchievementUI")
function AchievementButton_Localize(button)
	-- remove all other things about set point
	-- replace font object.
	button.Description:SetFontObject("GameFontHighlight")
	button.HiddenDescription:SetFontObject("GameFontHighlight")
end
```

**Comment by Meorawr** [comment]
I *think* this may have been fixed in 10.0.5.47481 but I can't actively test it. If you could confirm that'd be great, otherwise I'll close this ticket in a few days and assume it's fixed.

**Comment by EKE00372** [comment]
Still didnt fix in 47481 :/

**Comment by EKE00372** [comment]
still in retail 49426

**Comment by EKE00372** [comment]
confrim issue still in 10.1.5.49719 PTR

**Comment by EKE00372** [comment]
issue still in 10.2.0.51239

can we get fix in year?

**Comment by EKE00372** [comment]
still in tww alpha.

don't need these unnecessary localization changes.
https://github.com/Gethe/wow-ui-source/blob/live/Interface/AddOns/Blizzard_AchievementUI/Mainline/Localization.lua#L47

**Comment by EKE00372** [comment]
Fixed in 11.0.0.55087. Soon.
